# Contains jobs corresponding to Oppiabot.

name: Oppiabot

on:
  pull_request_target:
    branches:
      - develop

jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CLA Check
        uses: oppia/oppiabot@1.2.0
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
